language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - travis_retry pip install -r requirements/base.txt -r requirements/dev.txt
  - pip install coveralls

script: coverage run -m pytest

after_success:
  coveralls
