language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - travis_retry pip install -r requirements/base.txt -r requirements/dev.txt
  - pip install coveralls

script: coverage run -m pytest

after_success:
  coveralls
